project:
  type: website
  output-dir: docs

website:
  title: "R Latinoamérica Blog"
  # sidebar:
  #   style: "docked"
  #   search: true
  navbar:
    logo: "img/avatar.png"
    background: "#4b00ff"
    search: true
    pinned: true
    collapse: true
    right:
      - text: "Inicio"
        file: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/irwingss/
      - icon: person-plus-fill
        href: https://www.masterx.org/
format:
  html:
    theme: yeti
    css: styles.css

editor: source

